# Generated by Django 5.0.3 on 2024-04-11 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='efforts',
            field=models.TextField(default='', verbose_name='今日の頑張ったこと'),
        ),
        migrations.AddField(
            model_name='post',
            name='encouragement',
            field=models.TextField(default='', verbose_name='自分への励まし'),
        ),
    ]
