# Generated by Django 5.0.3 on 2024-04-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_post_efforts_post_encouragement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='無題', max_length=200),
        ),
    ]
